/**
 * Who (or what) wrote a commit, and how it reached the branch. Git records
 * no tokens or tool usage, so this reads the conventions AI tools leave
 * behind: co-author trailers ("Co-Authored-By: Claude"), generated-with
 * footers, agent author identities. A commit with none of them may still
 * be AI-assisted: the report says "marked", never "certainly".
 */

export interface AiMark {
  tool: string;
  /** The text that identified it, for showing the user why. */
  evidence: string;
}

export interface Landing {
  /** "pr" = merge commit or squash with (#N); "push" = committed straight to the branch. */
  via: "pr" | "push";
  pr?: number;
  /** PR title when the merge message carries it. */
  title?: string;
}

interface Rule {
  tool: string;
  /** Tested against the whole message (subject + body). */
  message?: RegExp;
  /** Tested against "name <email>". */
  identity?: RegExp;
}

// Order matters: specific tools before generic "AI" markers.
const RULES: Rule[] = [
  { tool: "Claude Code", message: /Generated with \[?Claude Code/i },
  { tool: "Claude", message: /Co-Authored-By:[^\n]*(Claude|noreply@anthropic\.com)/i, identity: /noreply@anthropic\.com|^claude\[bot\]|claude-code/i },
  { tool: "GitHub Copilot", message: /Co-authored-by:[^\n]*copilot/i, identity: /copilot-swe-agent|copilot\[bot\]|github-copilot/i },
  { tool: "Cursor", message: /Co-authored-by:[^\n]*cursor|Generated (with|by) Cursor/i, identity: /cursoragent@cursor\.com|\bcursor agent\b/i },
  { tool: "OpenAI Codex", message: /Co-authored-by:[^\n]*codex|Generated (with|by) Codex/i, identity: /chatgpt-codex-connector|codex\[bot\]/i },
  { tool: "Devin", identity: /devin-ai-integration/i, message: /Co-authored-by:[^\n]*devin/i },
  { tool: "Aider", message: /^aider: |Co-authored-by:[^\n]*aider/im, identity: /\(aider\)/i },
  { tool: "Gemini", message: /Co-authored-by:[^\n]*gemini|Generated (with|by) Gemini/i, identity: /gemini-code-assist/i },
  { tool: "Windsurf", message: /Co-authored-by:[^\n]*(windsurf|codeium)/i },
  { tool: "Amazon Q", message: /Co-authored-by:[^\n]*amazon q/i, identity: /amazon-q-developer/i },
  { tool: "AI tool", message: /🤖 Generated with|Generated by AI|AI-generated/i },
];

/** Automation that isn't an AI writing code: dependency bumps, release bots. */
const BOTS = /\b(dependabot|renovate|github-actions|greenkeeper|snyk-bot|semantic-release|release-please|pre-commit-ci|mergify|imgbot|allcontributors)\b|\[bot\]/i;

export function detectAi(c: { author: string; email: string; subject: string; body: string }): AiMark | undefined {
  const message = `${c.subject}\n${c.body}`;
  const identity = `${c.author} <${c.email}>`;
  for (const r of RULES) {
    const m = r.message?.exec(message);
    if (m) return { tool: r.tool, evidence: (message.split("\n").find((l) => r.message!.test(l)) ?? m[0]).trim().slice(0, 120) };
    if (r.identity?.test(identity)) return { tool: r.tool, evidence: `author ${identity}`.slice(0, 120) };
  }
  return undefined;
}

export function detectBot(c: { author: string; email: string }): string | undefined {
  const identity = `${c.author} <${c.email}>`;
  return BOTS.test(identity) ? c.author.replace(/\[bot\]$/, "") : undefined;
}

/**
 * How a first-parent commit got onto the branch. GitHub's merge commits say
 * "Merge pull request #N from ..." with the PR title as the body; squash and
 * rebase merges end the subject with "(#N)". Anything else was pushed directly.
 */
export function landing(c: { subject: string; body: string; parents: number }): Landing {
  const merge = /^Merge pull request #(\d+)/.exec(c.subject);
  if (merge) return { via: "pr", pr: Number(merge[1]), title: c.body.split("\n")[0]?.trim() || undefined };
  const squash = /\(#(\d+)\)\s*$/.exec(c.subject);
  if (squash) return { via: "pr", pr: Number(squash[1]), title: c.subject.replace(/\s*\(#\d+\)\s*$/, "") };
  const glMerge = /^Merge branch '.*' into .*/.test(c.subject) && /See merge request .*!(\d+)/.exec(c.body);
  if (glMerge) return { via: "pr", pr: Number(glMerge[1]), title: c.body.split("\n")[0]?.trim() || undefined };
  return { via: "push" };
}
